#!/bin/bash

THIS=$0
PROG_PATH=${THIS%/*}
DIR="$( cd "$( dirname "$0" )" && pwd )"

host=`hostname`
host=${host%%\.*}
host=${host/-/_}
echo host: $host

buckeye_CONTENT_ROOT="/local/tomcat"
sour_CONTENT_ROOT="/home/users/kamb/sdis"
hazy_CONTENT_ROOT="/usr/local/src/oads/tomcat"

content_var="${host}_CONTENT_ROOT"
echo content_var = $content_var

OA_DOCUMENT_ROOT="${!content_var}"
echo "CONTENT_ROOT $OA_DOCUMENT_ROOT"
if [ ! "$OA_DOCUMENT_ROOT" ] ; then
	echo No content root found for host $host
	exit 1
fi
OA_DOC_PROP="-DOA_DOCUMENT_ROOT=${OA_DOCUMENT_ROOT}"

STD_LOC=content/OAPUploadDashboard/bin

buckeye_APP_CONTENT="${OA_DOCUMENT_ROOT}/${STD_LOC}"
sour_APP_CONTENT="${OA_DOCUMENT_ROOT}/${STD_LOC}"
hazy_APP_CONTENT="${OA_DOCUMENT_ROOT}/${STD_LOC}"

APP_CONTENT="${host}_APP_CONTENT"

CLIENT_JAR="${DIR}/admin-client.jar"
echo client jar: $CLIENT_JAR

# OAP_ENV=-Doap.env=matisse 
# DEBUG_CONFIG=-Dconfiguration_debug 

cmd="java ${DEBUG_CONFIG} ${OA_DOC_PROP} ${OAP_ENV} -jar ${CLIENT_JAR} $@"
echo cmd: $cmd
java ${DEBUG_CONFIG} ${OA_DOC_PROP} ${OAP_ENV} -jar ${CLIENT_JAR} "$@"


