#!/bin/bash
#
# This script makes all the changes necessary to add a user to the SADashboard
# Tomcat db users and roles, OAPDashboard user files, etc.

# 
# dunkel:
#	mysql:
#		database: oapdashboard
#			table:	TomcatUsers
#				username, password
#			table:	Roles
#				role, description
#			table: TomcatRoles
#				user_dbid, username, role_dbid, userrole
#		database: OAPFlags
#			table: Reviewers
#				username, realname, email
#
#	tomcat:
#		NOT USING: TomcatRoles.xml
#		using MySQL
#	
#	dashboard:
#		~kamb/tomcat/70/content/OAPUploadDashboard/config/OAPUploadDashboard.properties
#			RoleFor_[user_name]=[Admin|User(?)]

OS=`uname -a | awk '{ print $1 }'`

OA_FILE=~kamb/tomcat/70/content/OAPUploadDashboard/config/OAPUploadDashboard.properties
if [ 'Darwin' == "$OS" ] ; then
	echo "Running on Darwin.  Using Postgres"
	OA_FILE=~kamb/tomcat/7/content/OAPUploadDashboard/config/OAPUploadDashboard.properties
fi

usage() {
	echo add_user [username] [real name] [email]
}


echo args $#  $@


if [ $# != 3 ] ; then
	usage
	exit
fi

username=$1
realname=$2
email=$3

echo -n "Please enter user password: "
read -s user_passwd
echo
echo -n "MySQL Password: "
read -s ms_passwd
echo

echo username: $username
echo Real Name: $realname
echo user email: $email
echo -n "Is this correct? [yN] "
read yesno

if [ "y" != "$yesno" ] ; then
	echo exiting
	exit
fi

echo checking for $username in $OA_FILE

if [ -e $OA_FILE ] ; then
	exists=`grep $username $OA_FILE`
	if [ $exists ] ; then
		echo $username already added to OA config file as: $exists
	else
		echo adding $username as Admin to OA config
		echo "RoleFor_"${username}"=Admin" >> $OA_FILE
	fi
else
	echo "OA config file not found: " + $OA_FILE
fi

SQL_FILE=add_user-tomcat.sql

DASH_DB=oapdashboard
FLAG_DB=OAPFlags
OA_USER_ROLE=oapdashboarduser
USE=use

DB=mysql
DB_USER="-u scientist"
PASSWD="--password=${ms_passwd}"

if [ 'Darwin' == "$OS" ] ; then
	DB=psql
	DB_USER="-U oapweb"
	PASSWD="-w"
	USE="\connect"
fi


echo creating sql file $SQL_FILE
if [ -e $SQL_FILE ] ; then
	rm $SQL_FILE
fi

echo "$USE  $DASH_DB;" > $SQL_FILE
echo "insert into TomcatUsers ( username, password ) values ( '$username', '$user_passwd' );" >> $SQL_FILE
echo "insert into TomcatRoles ( user_dbid, username, role_dbid, userrole ) values ("\
"(select db_id from TomcatUsers where username = '${username}'), '${username}', "\
"(select db_id from Roles where role='$OA_USER_ROLE'), '$OA_USER_ROLE');" >> $SQL_FILE

echo "$USE  $FLAG_DB;" >> $SQL_FILE
echo "insert into Reviewers ( username, realname, email ) values ( '$username', '$realname', '$email' );" >> $SQL_FILE

echo "${DB} ${DB_USER} $PASSWD $DASH_DB"

${DB} ${DB_USER} $PASSWD $DASH_DB < $SQL_FILE

# rm $SQL_FILE

